version: "3.9"

services:

  servicea:
    image: service-kong:latest
    environment:
      PORT: ":8081"
      CONTENT: "Service A"
    ports:
      - 8081:8081

  serviceb:
    image: service-kong:latest
    environment:
      PORT: ":8082"
      CONTENT: "Service b"
    ports:
      - 8082:8082

  servicec:
    image: service-kong:latest
    environment:
      PORT: ":8083"
      CONTENT: "Service C"
    ports:
      - 8083:8083
