#extensions:
#  basicauth/logs:
#    client_auth:
#      username: "${LOGS_USER_ID}"
#      password: "${TOKEN}"

receivers:
  otlp:
    protocols:
      http:
      #grpc:

processors:
  batch:
    send_batch_max_size: 1000
    send_batch_size: 100
    timeout: 10s

exporters:
#  logging:
#    verbosity: detailed # detailed, normal or basic
#  loki:
#    endpoint: http://localhost:3100/loki/api/v1/push
#    tls:
#      insecure: true
#    labels:
#      attributes:
#        host.name: host_name
#    format: json
#    tenant:
#      source: attributes
#      value: tenant
#  loki: #Grafana Cloud
#    endpoint: "${LOGS_URL}"
#    auth:
#      authenticator: basicauth/logs
  datadog:
    api:
      fail_on_invalid_key: true
      site: us5.datadoghq.com #DataDog free tier
      #site: datadoghq.com #DataDog PRD
      key: <API_KEY>
      
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog]
